Exception: icontrol_driver: instance names and partitions cannot contain '/'
Issues:
Fixes #91

Problem:
SNAT names created in common partition incorrectly have '/Common/' preprended
to name, causing invalid name exception.

Analysis: This is an artifact from v1 code and does not apply to
v2 code using the f5-sdk. Removed code to prepend Common.

Tests: