Fixes AttributeError: 'TunnelHandler' object has no attribute '_CacheBase__lock_acquired'
Issues:
Fixes #<issueid>

Problem:
* AttributeError: 'TunnelHandler' object has no attribute
        '_CacheBase__lock_acquired'
* set_context schema is no longer needed with TunnelHandler

Analysis:
* TunnelHandler.__init__ was not calling super().__init__
* set_context passing is removed from manager, controller, and network
        modules

Tests:
We should now see that agent not have any issues starting up