Revert of the L2 population refactor
Revert "Performs several efficiency enhancements"

This reverts commit b038eb35da85ff2e64484e8c1912cf49bf6e2437.

Revert "Adding HTTPError handling for remove_multipoint"

This reverts commit 99a47dee2af2c2ff534832a3f2f4c86d80ca9512.

Revert "Adding additional logging for efficiency"

This reverts commit e639fbef05caa5c18d0ac2429e0d630d69b64d3d.

Revert "Format fix for lvl of dict:dict:list:list for port"

This reverts commit cbbdf78eb1bdaf86e2cdb0dd1539fad21b1448b8.

Revert "Fixing gc.garbage() to gc.garbage"

This reverts commit 76e22d634e1b637671fa77d5a800c011eaa68884.

Revert "Bugfix: handling ReferenceError"

This reverts commit 21f4989a03e31637fafe8c1f8a58b96e9a1adcf3.

Revert "Fixing key error for new member vtep handling"

This reverts commit 49248db70f8b61f662c95e7aa97d52a7ed30f7cf.

Revert "Adding robust logger elements and fixing bugs"

This reverts commit 7df62058e3e7cbc6d55d48493fd283a2628b9905.

Revert "Many bug-fixes to get functional tests back online"

This reverts commit e5b89561f15d5e43e7449cb0e5fa8572f0581624.

Revert "WIP: bugfix typo of netowrk_type instead of network_type"

This reverts commit 299b3585880f5bea45810413a2691d662478c608.

Revert "Bugfixes: Fixing further issues within the tunnels"

This reverts commit 56644b224c3c14ac5a80f1badeffbd406919258d.

Revert "Fixes AttributeError: 'TunnelHandler' object has no attribute '_CacheBase__lock_acquired'"

This reverts commit 4b980baf63b4580c96bb1e1913a8a05be6f671fe.

Revert "Adding tunnel/fdb deletion unit test"

This reverts commit e4e851b2615660cc96b5d039c613e617c0b4e3b0.

Revert "Consolidating failing tests"

This reverts commit 5cb740aa3e4d2159599bce8c8f1c3034ed69691d.

Revert "Fixing test_network_helper.py"

This reverts commit cca855577b1a5d66a68616e994b4c163a5aad794.

Revert "Refactor of the tunnels architecture"

This reverts commit 3ea943de6b4f0961b1f93cc82afe6db2c92e8413.